/** @fileoverview Machine-checkable planning contract for the U2A protocol catalogs. */

export const commandSchemaV1 = {
  "submit-plan-review": ["plan:PlanTargetV1", "governing_contract:GoverningContractTargetV1", "planning_pull_request:PullRequestTargetV1", "review_manifest:ReviewManifestV1", "readiness_artifact:ReadinessDeclarationV1"],
  "record-plan-review-dispatch": ["dispatch_id:Uuid"],
  "record-plan-review-verdict": ["reviewer_commit:GitSha"],
  "record-plan-decision": ["approval_locator:ApprovalLocatorV1"],
  "queue-approved-plan": ["approval_locator:ApprovalLocatorV1"],
  "acquire-work-lease": ["owner_id:Uuid", "session_id:Uuid", "workspace:WorkspaceTargetV1", "expires_at:UtcTimestamp"],
  "record-lease-heartbeat": ["lease_id:Uuid", "fencing_token:FencingTokenV1"],
  "takeover-work-lease": ["prior_lease_id:Uuid", "new_owner_id:Uuid", "new_session_id:Uuid", "expires_at:UtcTimestamp", "operator_override:boolean", "reason_code:LeaseReasonCodeV1"],
  "release-work-lease": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "reason_code:LeaseReasonCodeV1", "workspace:WorkspaceTargetV1", "evidence:ArtifactReferenceV1[]"],
  "submit-work-handoff": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "handoff:HandoffDecisionV1"],
  "record-review-findings": ["reviewed_head:GitSha", "review_output:ReviewOutputTargetV1", "repair_owner_id:Uuid", "repair_session_id:Uuid", "repair_expires_at:UtcTimestamp", "workspace:WorkspaceTargetV1", "handoff:HandoffDecisionV1"],
  "accept-review": ["reviewed_head:GitSha", "review_output:ReviewOutputTargetV1", "handoff:HandoffDecisionV1"],
  "invalidate-review": ["changed_artifacts:ArtifactReferenceV1[]"],
  "accept-learn": ["handoff:HandoffDecisionV1", "integration_owner_id:Uuid", "integration_session_id:Uuid", "integration_expires_at:UtcTimestamp", "workspace:WorkspaceTargetV1"],
  "return-for-repair": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "evidence:ArtifactReferenceV1[]", "repair_owner_id:Uuid", "repair_session_id:Uuid", "repair_expires_at:UtcTimestamp", "workspace:WorkspaceTargetV1", "handoff:HandoffDecisionV1"],
  "record-exact-merge": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "approved_head:GitSha", "merge_sha:GitSha", "evidence:ArtifactReferenceV1[]"],
  "record-verification-success": ["merge_sha:GitSha", "evidence:ArtifactReferenceV1[]"],
  "record-verification-failure": ["merge_sha:GitSha", "failure_code:VerificationFailureCodeV1", "evidence:ArtifactReferenceV1[]"],
  "resume-planning": ["resolution_code:ResolutionCodeV1", "evidence:ArtifactReferenceV1[]"],
  "resume-queued": ["resolution_code:ResolutionCodeV1", "evidence:ArtifactReferenceV1[]"],
  "pause-work": ["reason_code:LeaseReasonCodeV1", "workspace:WorkspaceTargetV1", "lease_target:LeaseTargetV1", "evidence:ArtifactReferenceV1[]"],
  "resume-work": ["workspace:WorkspaceTargetV1", "evidence:ArtifactReferenceV1[]"],
  "cancel-work": ["reason_code:LeaseReasonCodeV1", "workspace:WorkspaceTargetV1", "lease_target:LeaseTargetV1", "evidence:ArtifactReferenceV1[]"],
  "record-reconciliation-conflict": ["conflict_code:ErrorCodeV1", "evidence:ArtifactReferenceV1[]"],
  "record-review-scope-response": ["response:ReviewScopeResponseV1"],
  "record-gate-decision": ["gate:GateDecisionV1"],
  "record-process-finding": ["origin:ProcessFindingOriginV1", "affected_phase:LifecycleStateV1", "evidence_code:ProcessEvidenceCodeV1", "evidence_artifacts:ArtifactReferenceV1[]"],
  "dispose-process-finding": ["finding_id:Sha256", "disposition:ProcessFindingDispositionV1", "reason_code:ProcessEvidenceCodeV1", "repair_artifacts:ArtifactReferenceV1[]"],
  "supersede-process-finding-disposition": ["finding_id:Sha256", "prior_disposition_event_id:Uuid", "disposition:ProcessFindingDispositionV1", "reason_code:ProcessEvidenceCodeV1", "repair_artifacts:ArtifactReferenceV1[]"],
} as const;

export const eventValueSchemaV1 = {
  "plan-review-submitted": "ReviewManifestV1",
  "plan-review-dispatch-recorded": "ValidatedReviewDispatchV1",
  "plan-review-changes-required": "PlanReviewChangesRequiredValueV1",
  "plan-review-accepted": "ValidatedReviewEvidenceV1",
  "plan-decision-denied": "ApprovalEvidenceV1",
  "approved-plan-queued": "ApprovalEvidenceV1",
  "work-lease-acquired": "LeaseSnapshotV1",
  "lease-heartbeat-recorded": "LeaseSnapshotV1",
  "lease-revoked": "LeaseSnapshotV1",
  "work-lease-acquired-for-repair": "LeaseSnapshotV1",
  "integration-lease-acquired": "LeaseSnapshotV1",
  "work-handoff-submitted": "LeaseHandoffEffectV1",
  "review-findings-recorded": "HandoffDecisionV1",
  "review-accepted": "HandoffDecisionV1",
  "review-invalidated": "InvalidationEffectV1",
  "learn-accepted": "HandoffDecisionV1",
  "work-returned-for-repair": "HandoffDecisionV1",
  "exact-merge-recorded": "ExactMergeEffectV1",
  "verification-succeeded": "VerificationOutcomeV1",
  "verification-failed": "VerificationOutcomeV1",
  "planning-resumed": "InvalidationEffectV1",
  "queue-resumed": "ApprovalEvidenceV1",
  "work-paused": "LifecycleInterruptionEffectV1",
  "work-resumed": "LifecycleResumeEffectV1",
  "work-cancelled": "LifecycleInterruptionEffectV1",
  "reconciliation-conflict-recorded": "ReconciliationEffectV1",
  "review-scope-response-recorded": "ReviewScopeResponseV1",
  "gate-decision-recorded": "GateDecisionV1",
  "process-finding-recorded": "ProcessFindingV1",
  "process-finding-disposition-recorded": "FindingDispositionEffectV1",
  "process-finding-disposition-superseded": "FindingDispositionEffectV1",
} as const;

export const closedWireTypesV1 = [
  "ActorRoleV1", "ApprovalEvidenceV1", "ApprovalLocatorV1", "ApprovalRecord", "ApprovedWorkspaceRequirementV1", "ArtifactKindV1", "AuthorityScopeV1",
  "ArtifactProviderV1", "ArtifactReferenceV1", "BehaviorTraceDigestV1", "BranchNameV1",
  "CommandKindV1", "ErrorCodeV1", "ExecutionRequirementsV1", "ExactMergeEffectV1", "ExactMergeRecordV1",
  "ExcludedResponsibilityV1", "ExternalArtifactIdV1", "FailedReviewChoiceV1", "FailedReviewPolicyV1", "FencingCounterV1",
  "FencingTokenByResourceV1", "FencingTokenV1", "FindingDispositionEffectV1",
  "GateDecisionV1", "GateIdV1", "GateOutcomeV1", "GateRequirementV1", "GateValidityMillisecondsV1", "GitSha", "GoverningContractTargetV1",
  "HandoffBlockerCodeV1", "HandoffDecisionCodeV1", "HandoffDecisionV1", "HandoffKindV1",
  "HandoffOutcomeCodeV1", "InvalidationEffectV1",
  "LeaseHandoffEffectV1", "LeaseReasonCodeV1", "LeaseResourceV1", "LeaseSnapshotV1", "LeaseTargetV1",
  "LeaseTargetActiveV1", "LeaseTargetNoneV1",
  "LifecycleInterruptionEffectV1", "LifecycleResumeEffectV1", "LifecycleStateV1",
  "ModelNameV1", "NonnegativeSafeIntegerV1", "PlanReviewChangesRequiredValueV1", "PlanTargetV1", "PositiveSafeIntegerV1", "ProcessEvidenceCodeV1",
  "ProcessFindingDispositionV1", "ProcessFindingOriginV1", "ProcessFindingV1", "PullRequestNumberV1",
  "PullRequestTargetV1", "ReadinessDeclarationV1", "ReconciliationEffectV1",
  "RepoPath", "RepositorySlugV1", "ResolutionCodeV1", "ReviewChallengeLensV1", "ReviewManifestV1", "ReviewOutputTargetV1",
  "ReviewParticipantAttestationV1", "ReviewParticipantContextV1", "ReviewParticipantRoleV1", "ReviewerRoleV1",
  "ReviewRiskAlternativeDifferenceV1", "ReviewRiskHighUnavailableV1", "ReviewRiskHighUsedV1", "ReviewRiskPolicyV1", "ReviewRiskStandardV1",
  "ReviewScopeChoiceV1", "ReviewScopeDecisionV1", "ReviewScopeFifthChoiceV1", "ReviewScopeLineageV1", "ReviewScopeResponseV1",
  "ReviewScopeThirdResponseV1", "ReviewSessionIdentityV1", "ReviewVerdictV1", "ReviewWriteV1", "ScopeBehaviorIdV1",
  "Sha256", "UtcTimestamp", "Uuid", "ValidatedReviewDispatchV1",
  "ValidatedReviewEvidenceV1", "VerificationFailedV1", "VerificationFailureCodeV1", "VerificationOutcomeV1", "VerificationSucceededV1",
  "TrustedAdapterAttestationV1", "TrustedAdapterIssuerKindV1", "TrustedPrincipalV1", "VerifiedReviewParticipantV1", "WorkspaceTargetV1", "boolean",
] as const;

/** Every closed type has one machine-readable recursive definition or exact scalar/union rule. */
export const recursiveWireSchemaV1: Readonly<Record<(typeof closedWireTypesV1)[number], readonly string[] | string>> = {
  ActorRoleV1: "closed-enum:operator|phase-agent|worker|reviewer|control-plane",
  ApprovalEvidenceV1: ["record:ApprovalRecord", "source:ArtifactReferenceV1", "trust:TrustedAdapterAttestationV1"],
  ApprovalLocatorV1: ["issue_id:Uuid", "commit:GitSha"],
  ApprovalRecord: "external-closed-type:architecture-standard/approval-record",
  ApprovedWorkspaceRequirementV1: ["branch:BranchNameV1", "head:reviewed-plan-commit"],
  ArtifactKindV1: "closed-enum:artifact-kind-catalog",
  ArtifactProviderV1: "closed-enum:git|git-issue|github|codex|local",
  ArtifactReferenceV1: ["kind:ArtifactKindV1", "path:RepoPath|null", "commit:GitSha|null", "digest:Sha256", "provider:ArtifactProviderV1|null", "external_id:ExternalArtifactIdV1|null"],
  AuthorityScopeV1: "closed-enum:authority-scope-catalog",
  BehaviorTraceDigestV1: ["behavior_id:ScopeBehaviorIdV1", "trace_digest:Sha256"],
  BranchNameV1: "ascii:git-branch-ref:1..255",
  CommandKindV1: "closed-enum:commandSchemaV1-keys",
  ErrorCodeV1: "closed-enum:plan-error-catalog",
  ExcludedResponsibilityV1: "closed-enum:sqlite|durable-storage|checkpoint-io|provider-adapters|server|git-io|ui",
  ExecutionRequirementsV1: ["dependency_issue_ids:Uuid[]", "approved_workspace:ApprovedWorkspaceRequirementV1", "required_gates:GateRequirementV1[]", "declaration_digest:Sha256"],
  ExactMergeEffectV1: ["merge:ExactMergeRecordV1", "revoked_lease:LeaseSnapshotV1", "resulting_last_fencing_token_by_resource:FencingTokenByResourceV1"],
  ExactMergeRecordV1: ["approved_head:GitSha", "merge_sha:GitSha", "evidence:ArtifactReferenceV1[]"],
  ExternalArtifactIdV1: "ascii:printable:1..256:non-secret-provider-opaque-id",
  FailedReviewChoiceV1: ["event_id:Uuid", "response:ReviewScopeResponseV1"],
  FailedReviewPolicyV1: ["changes_required_count:NonnegativeSafeIntegerV1", "third_review_response:ReviewScopeResponseV1|null", "fifth_review_choices:FailedReviewChoiceV1[]", "active_permit_choice_event_id:Uuid|null", "consumed_permit_choice_event_ids:Uuid[]"],
  FencingCounterV1: "decimal:uint64-nonnegative:no-leading-zero",
  FencingTokenByResourceV1: ["work:FencingCounterV1", "integration:FencingCounterV1"],
  FindingDispositionEffectV1: ["finding:ProcessFindingV1", "invalidation:InvalidationEffectV1|null"],
  FencingTokenV1: "decimal:uint64-positive:no-leading-zero",
  GateDecisionV1: ["gate_id:GateIdV1", "definition_digest:Sha256", "input_digests:Sha256[]", "target_revision:GitSha", "outcome:GateOutcomeV1", "evidence:ArtifactReferenceV1[]", "decided_at:UtcTimestamp"],
  GateIdV1: "ascii:lower-kebab:1..64",
  GateOutcomeV1: "closed-enum:passed|failed",
  GateRequirementV1: ["gate_id:GateIdV1", "definition_digest:Sha256", "valid_for_ms:GateValidityMillisecondsV1"],
  GateValidityMillisecondsV1: "json-integer:1..86400000",
  GitSha: "ascii:lower-hex:40:nonzero",
  GoverningContractTargetV1: ["path:PLANS.md", "commit:GitSha", "digest:Sha256"],
  HandoffBlockerCodeV1: "closed-enum:none|tests-failed|review-findings|gate-failed|approval-stale|reconciliation-required",
  HandoffDecisionCodeV1: "closed-enum:scope-complete|tests-passed|review-clean|learning-recorded|repair-required|operator-directed",
  HandoffDecisionV1: ["kind:HandoffKindV1", "source_session_id:Uuid", "target_session_id:Uuid|null", "target_revision:GitSha", "outcome_code:HandoffOutcomeCodeV1", "decision_codes:HandoffDecisionCodeV1[]", "blocker_codes:HandoffBlockerCodeV1[]", "mutation_artifacts:ArtifactReferenceV1[]", "evidence:ArtifactReferenceV1[]", "next_transition:CommandKindV1"],
  HandoffKindV1: "closed-enum:implementation|review-findings|review-clean|learn-complete|repair-return",
  HandoffOutcomeCodeV1: "closed-enum:ready-for-review|changes-required|review-accepted|ready-to-merge|returned-for-repair",
  InvalidationEffectV1: ["review:ValidatedReviewEvidenceV1|null", "approval:ApprovalEvidenceV1|null", "gates:GateDecisionV1[]", "resulting_state:LifecycleStateV1"],
  LeaseHandoffEffectV1: ["handoff:HandoffDecisionV1", "revoked_lease:LeaseSnapshotV1|null", "acquired_lease:LeaseSnapshotV1|null", "resulting_last_fencing_token_by_resource:FencingTokenByResourceV1"],
  LeaseReasonCodeV1: "closed-enum:lease-reason-catalog",
  LeaseResourceV1: "closed-enum:work|integration",
  LeaseSnapshotV1: ["lease_id:Uuid", "resource:LeaseResourceV1", "workspace:WorkspaceTargetV1", "owner_id:Uuid", "session_id:Uuid", "acquired_at:UtcTimestamp", "expires_at:UtcTimestamp", "fencing_token:FencingTokenV1", "last_heartbeat_at:UtcTimestamp|null", "revoked_at:UtcTimestamp|null", "reason_code:LeaseReasonCodeV1|null"],
  LeaseTargetV1: "closed-union:LeaseTargetNoneV1|LeaseTargetActiveV1",
  LeaseTargetActiveV1: ["kind:with-active-lease", "lease_id:Uuid", "fencing_token:FencingTokenV1"],
  LeaseTargetNoneV1: "closed-object:kind=without-active-lease",
  LifecycleInterruptionEffectV1: ["reason_code:LeaseReasonCodeV1", "workspace:WorkspaceTargetV1", "evidence:ArtifactReferenceV1[]", "revoked_lease:LeaseSnapshotV1|null", "resulting_last_fencing_token_by_resource:FencingTokenByResourceV1"],
  LifecycleResumeEffectV1: ["workspace:WorkspaceTargetV1", "approval:ApprovalEvidenceV1", "gates:GateDecisionV1[]", "evidence:ArtifactReferenceV1[]", "resulting_active_lease:null", "resulting_last_fencing_token_by_resource:FencingTokenByResourceV1"],
  LifecycleStateV1: "closed-enum:lifecycle-state-catalog",
  ModelNameV1: "ascii:printable:1..128",
  NonnegativeSafeIntegerV1: "json-integer:0..9007199254740991",
  PlanReviewChangesRequiredValueV1: ["review:ValidatedReviewEvidenceV1", "policy:FailedReviewPolicyV1"],
  PlanTargetV1: ["path:RepoPath", "commit:GitSha", "digest:Sha256"],
  PositiveSafeIntegerV1: "json-integer:1..9007199254740991",
  ProcessEvidenceCodeV1: "ascii:kebab:1..64",
  ProcessFindingDispositionV1: "closed-enum:execution-deviation|issue-contract-gap|product-contract-gap|operating-contract-gap|no-reusable-change",
  ProcessFindingOriginV1: "closed-enum:operator-correction|agent-error|review-finding|interruption|unexpected-delay",
  ProcessFindingV1: ["finding_id:Sha256", "origin:ProcessFindingOriginV1", "affected_phase:LifecycleStateV1", "evidence_code:ProcessEvidenceCodeV1", "evidence_artifacts:ArtifactReferenceV1[]", "disposition:ProcessFindingDispositionV1|null", "repair_artifacts:ArtifactReferenceV1[]", "disposition_event_id:Uuid|null", "supersedes_event_id:Uuid|null"],
  PullRequestNumberV1: "json-integer:1..2147483647",
  PullRequestTargetV1: ["provider:github", "repository:RepositorySlugV1", "number:PullRequestNumberV1", "head:GitSha"],
  ReadinessDeclarationV1: ["artifact:ArtifactReferenceV1", "plan:PlanTargetV1", "issue_id:Uuid", "lineage_id:Sha256", "behavior_trace_digests:BehaviorTraceDigestV1[]"],
  ReconciliationEffectV1: ["conflict_code:ErrorCodeV1", "evidence:ArtifactReferenceV1[]", "revoked_lease:LeaseSnapshotV1|null", "resulting_last_fencing_token_by_resource:FencingTokenByResourceV1"],
  RepoPath: "utf8:nfc:relative-slash-path:1..1024",
  RepositorySlugV1: "ascii:owner/name:3..201",
  ResolutionCodeV1: "closed-enum:intent-changed|source-reconciled|runtime-blocker-cleared|operator-directed",
  ReviewChallengeLensV1: "closed-enum:plans-conformance|novice-executability|security|data-integrity|adversarial-counterexample|pure-domain-boundary|deterministic-replay",
  ReviewManifestV1: ["plan:PlanTargetV1", "governing_contract:GoverningContractTargetV1", "execution_requirements:ExecutionRequirementsV1", "complete_prompt:ArtifactReferenceV1", "complete_prompt_digest:Sha256", "reviewer_role:ReviewerRoleV1", "reviewer:ReviewSessionIdentityV1", "challenge_lenses:ReviewChallengeLensV1[]", "output_path:RepoPath", "author_attestations:ReviewParticipantAttestationV1[]", "reviser_attestations:ReviewParticipantAttestationV1[]", "reviewer_attestation:ReviewParticipantAttestationV1", "risk_policy:ReviewRiskPolicyV1", "dispatch_id:Uuid"],
  ReviewOutputTargetV1: ["path:RepoPath", "commit:GitSha", "digest:Sha256", "verdict:ReviewVerdictV1"],
  ReviewParticipantAttestationV1: ["participant:ReviewSessionIdentityV1", "role:ReviewParticipantRoleV1", "context_source:ReviewParticipantContextV1", "attestation:ArtifactReferenceV1"],
  ReviewParticipantContextV1: "closed-enum:originating|fresh-isolated",
  ReviewParticipantRoleV1: "closed-enum:author|reviser|reviewer",
  ReviewerRoleV1: "utf8:nfc:1..128",
  ReviewRiskAlternativeDifferenceV1: "closed-enum:provider|model|both",
  ReviewRiskHighUnavailableV1: ["risk:high", "alternative:unavailable", "limitation:ArtifactReferenceV1"],
  ReviewRiskHighUsedV1: ["risk:high", "alternative:used", "difference:ReviewRiskAlternativeDifferenceV1"],
  ReviewRiskPolicyV1: "closed-union:ReviewRiskStandardV1|ReviewRiskHighUsedV1|ReviewRiskHighUnavailableV1",
  ReviewRiskStandardV1: "closed-object:risk=standard,alternative=not-required",
  ReviewScopeChoiceV1: "closed-enum:split|redesign|permit-one-more",
  ReviewScopeDecisionV1: "closed-enum:keep-scope|split|redesign",
  ReviewScopeFifthChoiceV1: ["kind:fifth-review-choice", "plan:PlanTargetV1", "lineage:ReviewScopeLineageV1", "choice:ReviewScopeChoiceV1", "evidence:ArtifactReferenceV1[]"],
  ReviewScopeLineageV1: ["decision:ReviewScopeDecisionV1", "retained_issue_id:Uuid", "predecessor_plan:PlanTargetV1", "successor_issue_ids:Uuid[]", "behavior_ids:ScopeBehaviorIdV1[]", "excluded_responsibilities:ExcludedResponsibilityV1[]", "lineage_id:Sha256", "declaration_artifact:ArtifactReferenceV1"],
  ReviewScopeResponseV1: "closed-union:ReviewScopeThirdResponseV1|ReviewScopeFifthChoiceV1",
  ReviewScopeThirdResponseV1: ["kind:third-review-response", "plan:PlanTargetV1", "lineage:ReviewScopeLineageV1", "readiness_artifact:ReadinessDeclarationV1", "scope_decision:ReviewScopeDecisionV1", "evidence:ArtifactReferenceV1[]"],
  ReviewSessionIdentityV1: ["session_id:Uuid", "provider:ArtifactProviderV1", "model:ModelNameV1|null"],
  ReviewVerdictV1: "closed-enum:clean|changes-required",
  ReviewWriteV1: ["path:RepoPath", "digest:Sha256"],
  ScopeBehaviorIdV1: "closed-enum:interpret-request|reject-invalid-order|control-active-agent|bind-clean-review|bind-operator-approval|limit-failed-reviews|handoff-to-storage",
  Sha256: "ascii:lower-hex:64:nonzero",
  UtcTimestamp: "ascii:rfc3339-utc-milliseconds:24",
  Uuid: "ascii:rfc4122-v4-lowercase:36",
  TrustedAdapterAttestationV1: ["issuer_id:Uuid", "issuer_kind:TrustedAdapterIssuerKindV1", "authenticated_at:UtcTimestamp", "transport_identity_digest:Sha256", "configured_repository_digest:Sha256", "subject_digest:Sha256", "source:ArtifactReferenceV1"],
  TrustedAdapterIssuerKindV1: "closed-enum:local-transport|git-adapter|provider-adapter|clock-adapter|workspace-adapter",
  TrustedPrincipalV1: ["actor_id:Uuid", "role:ActorRoleV1", "session_id:Uuid", "authority_scopes:AuthorityScopeV1[]", "authenticated_at:UtcTimestamp", "transport_identity_digest:Sha256", "trust:TrustedAdapterAttestationV1"],
  ValidatedReviewDispatchV1: ["dispatch_id:Uuid", "prompt_digest:Sha256", "reviewer:ReviewSessionIdentityV1", "provider:ArtifactProviderV1", "model:ModelNameV1|null", "dispatched_at:UtcTimestamp", "receipt:ArtifactReferenceV1", "trust:TrustedAdapterAttestationV1"],
  ValidatedReviewEvidenceV1: ["manifest:ReviewManifestV1", "dispatch:ValidatedReviewDispatchV1", "output:ReviewOutputTargetV1", "reviewer_commit:GitSha", "sole_write:ReviewWriteV1", "reviewer:ReviewSessionIdentityV1", "authors:ReviewSessionIdentityV1[]", "revisers:ReviewSessionIdentityV1[]", "challenge_lenses:ReviewChallengeLensV1[]", "risk_policy:ReviewRiskPolicyV1", "attestation_digests:Sha256[]", "bundle_digest:Sha256", "execution_requirements:ExecutionRequirementsV1", "required_gates:GateRequirementV1[]", "verdict:ReviewVerdictV1"],
  VerificationFailureCodeV1: "closed-enum:required-check-failed|merge-mismatch|post-merge-regression|source-unavailable",
  VerificationFailedV1: ["kind:failed", "merge_sha:GitSha", "failure_code:VerificationFailureCodeV1", "evidence:ArtifactReferenceV1[]"],
  VerificationOutcomeV1: "closed-union:VerificationSucceededV1|VerificationFailedV1",
  VerificationSucceededV1: ["kind:succeeded", "merge_sha:GitSha", "evidence:ArtifactReferenceV1[]"],
  VerifiedReviewParticipantV1: ["participant:ReviewSessionIdentityV1", "role:ReviewParticipantRoleV1", "context_source:ReviewParticipantContextV1", "attestation:ReviewWriteV1", "subject_binding_digest:Sha256"],
  WorkspaceTargetV1: ["workspace_id:Uuid", "branch:BranchNameV1", "head:GitSha", "path_digest:Sha256"],
  boolean: "json:boolean",
};

export type CommandKindV1 = keyof typeof commandSchemaV1;
export type EventKindV1 = keyof typeof eventValueSchemaV1;
