/** @fileoverview Machine-checkable planning contract for the U2A protocol catalogs. */

export const commandSchemaV1 = {
  "submit-plan-review": ["plan:PlanTargetV1", "governing_contract:GoverningContractTargetV1", "planning_pull_request:PullRequestTargetV1", "review_manifest:ReviewManifestV1", "readiness_artifact:ReadinessDeclarationV1"],
  "record-plan-review-dispatch": ["dispatch_id:Uuid"],
  "record-plan-review-verdict": ["reviewer_commit:GitSha"],
  "record-plan-decision": ["approval_locator:ApprovalLocatorV1"],
  "queue-approved-plan": ["approval_locator:ApprovalLocatorV1"],
  "acquire-work-lease": ["owner_id:Uuid", "session_id:Uuid", "workspace:WorkspaceTargetV1", "expires_at:UtcTimestamp"],
  "record-lease-heartbeat": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "observed_at:UtcTimestamp"],
  "takeover-work-lease": ["prior_lease_id:Uuid", "new_owner_id:Uuid", "new_session_id:Uuid", "expires_at:UtcTimestamp", "operator_override:boolean", "reason_code:LeaseReasonCodeV1"],
  "release-work-lease": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "reason_code:LeaseReasonCodeV1", "workspace:WorkspaceTargetV1", "evidence:ArtifactReferenceV1[]"],
  "submit-work-handoff": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "handoff:HandoffDecisionV1"],
  "record-review-findings": ["reviewed_head:GitSha", "review_output:ReviewOutputTargetV1", "repair_owner_id:Uuid", "repair_session_id:Uuid", "repair_expires_at:UtcTimestamp", "workspace:WorkspaceTargetV1", "handoff:HandoffDecisionV1"],
  "accept-review": ["reviewed_head:GitSha", "review_output:ReviewOutputTargetV1", "handoff:HandoffDecisionV1"],
  "invalidate-review": ["changed_artifacts:ArtifactReferenceV1[]"],
  "accept-learn": ["handoff:HandoffDecisionV1", "integration_owner_id:Uuid", "integration_session_id:Uuid", "integration_expires_at:UtcTimestamp", "workspace:WorkspaceTargetV1"],
  "return-for-repair": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "evidence:ArtifactReferenceV1[]", "repair_owner_id:Uuid", "repair_session_id:Uuid", "repair_expires_at:UtcTimestamp", "workspace:WorkspaceTargetV1", "handoff:HandoffDecisionV1"],
  "record-exact-merge": ["lease_id:Uuid", "fencing_token:FencingTokenV1", "approved_head:GitSha", "merge_sha:GitSha", "evidence:ArtifactReferenceV1[]"],
  "record-verification-success": ["merge_sha:GitSha", "evidence:ArtifactReferenceV1[]"],
  "record-verification-failure": ["merge_sha:GitSha", "failure_code:VerificationFailureCodeV1", "evidence:ArtifactReferenceV1[]"],
  "resume-planning": ["resolution_code:ResolutionCodeV1", "evidence:ArtifactReferenceV1[]"],
  "resume-queued": ["resolution_code:ResolutionCodeV1", "approval:ApprovalEvidenceV1", "evidence:ArtifactReferenceV1[]"],
  "pause-work": ["reason_code:LeaseReasonCodeV1", "workspace:WorkspaceTargetV1", "lease_target:LeaseTargetV1", "evidence:ArtifactReferenceV1[]"],
  "resume-work": ["workspace:WorkspaceTargetV1", "approval:ApprovalEvidenceV1", "gates:GateDecisionV1[]", "evidence:ArtifactReferenceV1[]"],
  "cancel-work": ["reason_code:LeaseReasonCodeV1", "workspace:WorkspaceTargetV1", "lease_target:LeaseTargetV1", "evidence:ArtifactReferenceV1[]"],
  "record-reconciliation-conflict": ["conflict_code:ErrorCodeV1", "evidence:ArtifactReferenceV1[]"],
  "record-review-scope-response": ["response:ReviewScopeResponseV1"],
  "record-gate-decision": ["gate:GateDecisionV1"],
  "record-process-finding": ["origin:ProcessFindingOriginV1", "affected_phase:LifecycleStateV1", "evidence_code:ProcessEvidenceCodeV1", "evidence_artifacts:ArtifactReferenceV1[]"],
  "dispose-process-finding": ["finding_id:Sha256", "disposition:ProcessFindingDispositionV1", "reason_code:ProcessEvidenceCodeV1", "repair_artifacts:ArtifactReferenceV1[]"],
  "supersede-process-finding-disposition": ["finding_id:Sha256", "prior_disposition_event_id:Uuid", "disposition:ProcessFindingDispositionV1", "reason_code:ProcessEvidenceCodeV1", "repair_artifacts:ArtifactReferenceV1[]"],
} as const;

export const eventValueSchemaV1 = {
  "plan-review-submitted": "ReviewManifestV1",
  "plan-review-dispatch-recorded": "ValidatedReviewDispatchV1",
  "plan-review-changes-required": "PlanReviewChangesRequiredValueV1",
  "plan-review-accepted": "ValidatedReviewEvidenceV1",
  "plan-decision-denied": "ApprovalEvidenceV1",
  "approved-plan-queued": "ApprovalEvidenceV1",
  "work-lease-acquired": "LeaseSnapshotV1",
  "lease-heartbeat-recorded": "LeaseSnapshotV1",
  "lease-revoked": "LeaseSnapshotV1",
  "work-lease-acquired-for-repair": "LeaseSnapshotV1",
  "integration-lease-acquired": "LeaseSnapshotV1",
  "work-handoff-submitted": "LeaseHandoffEffectV1",
  "review-findings-recorded": "HandoffDecisionV1",
  "review-accepted": "HandoffDecisionV1",
  "review-invalidated": "InvalidationEffectV1",
  "learn-accepted": "HandoffDecisionV1",
  "work-returned-for-repair": "HandoffDecisionV1",
  "exact-merge-recorded": "ExactMergeEffectV1",
  "verification-succeeded": "VerificationOutcomeV1",
  "verification-failed": "VerificationOutcomeV1",
  "planning-resumed": "InvalidationEffectV1",
  "queue-resumed": "ApprovalEvidenceV1",
  "work-paused": "LifecycleInterruptionEffectV1",
  "work-resumed": "LifecycleResumeEffectV1",
  "work-cancelled": "LifecycleInterruptionEffectV1",
  "reconciliation-conflict-recorded": "ReconciliationEffectV1",
  "review-scope-response-recorded": "ReviewScopeResponseV1",
  "gate-decision-recorded": "GateDecisionV1",
  "process-finding-recorded": "ProcessFindingV1",
  "process-finding-disposition-recorded": "FindingDispositionEffectV1",
  "process-finding-disposition-superseded": "FindingDispositionEffectV1",
} as const;

export const closedWireTypesV1 = [
  "ApprovalEvidenceV1", "ApprovalLocatorV1", "ArtifactReferenceV1", "ErrorCodeV1",
  "ExactMergeEffectV1", "FindingDispositionEffectV1", "FencingTokenV1", "GateDecisionV1",
  "GitSha", "GoverningContractTargetV1", "HandoffDecisionV1", "InvalidationEffectV1",
  "LeaseHandoffEffectV1", "LeaseReasonCodeV1", "LeaseSnapshotV1", "LeaseTargetV1",
  "LifecycleInterruptionEffectV1", "LifecycleResumeEffectV1", "LifecycleStateV1",
  "PlanReviewChangesRequiredValueV1", "PlanTargetV1", "ProcessEvidenceCodeV1",
  "ProcessFindingDispositionV1", "ProcessFindingOriginV1", "ProcessFindingV1",
  "PullRequestTargetV1", "ReadinessDeclarationV1", "ReconciliationEffectV1",
  "ResolutionCodeV1", "ReviewManifestV1", "ReviewOutputTargetV1", "ReviewScopeResponseV1",
  "Sha256", "UtcTimestamp", "Uuid", "ValidatedReviewDispatchV1",
  "ValidatedReviewEvidenceV1", "VerificationFailureCodeV1", "VerificationOutcomeV1",
  "WorkspaceTargetV1", "boolean",
] as const;

export type CommandKindV1 = keyof typeof commandSchemaV1;
export type EventKindV1 = keyof typeof eventValueSchemaV1;
